mytest:code.cc
	g++ -o $@ $^ -O1

.PHONY:clean
clean:
	rm -rf mytest



# .PHONY:all
# all:client server

# client:client.cc 
# 	g++ -o $@ $^

# server:server.cc  
# 	g++ -o $@ $^

# .PHONY:clean
# clean:
# 	rm -rf clean server

